/*
 * Chore board tasks: chore name -> [farmActivity counter, amount]. GENERATED from the game
 * source, types/choreBoard.ts NPC_CHORES (sunflower-land cb713bc, 2026-09-29) — every entry there
 * is a farmActivityTask. The game counts a chore as farmActivity[counter] - chore.initialProgress
 * (getChoreProgress), so this is all it takes to know how far along a chore is.
 */
export const CHORE_TASKS = {
  "Harvest Sunflowers 150 times": ["Sunflower Harvested", 150],
  "Harvest Sunflowers 200 times": ["Sunflower Harvested", 200],
  "Harvest Sunflowers 250 times": ["Sunflower Harvested", 250],
  "Harvest Sunflowers 300 times": ["Sunflower Harvested", 300],
  "Harvest Sunflowers 350 times": ["Sunflower Harvested", 350],
  "Harvest Potatoes 100 times": ["Potato Harvested", 100],
  "Harvest Potatoes 125 times": ["Potato Harvested", 125],
  "Harvest Potatoes 130 times": ["Potato Harvested", 130],
  "Harvest Potatoes 150 times": ["Potato Harvested", 150],
  "Harvest Potatoes 175 times": ["Potato Harvested", 175],
  "Harvest Potatoes 200 times": ["Potato Harvested", 200],
  "Harvest Potatoes 225 times": ["Potato Harvested", 225],
  "Harvest Potatoes 250 times": ["Potato Harvested", 250],
  "Harvest Rhubarbs 100 times": ["Rhubarb Harvested", 100],
  "Harvest Rhubarbs 125 times": ["Rhubarb Harvested", 125],
  "Harvest Rhubarbs 150 times": ["Rhubarb Harvested", 150],
  "Harvest Rhubarbs 200 times": ["Rhubarb Harvested", 200],
  "Harvest Rhubarbs 250 times": ["Rhubarb Harvested", 250],
  "Harvest Rhubarbs 300 times": ["Rhubarb Harvested", 300],
  "Harvest Pumpkins 100 times": ["Pumpkin Harvested", 100],
  "Harvest Pumpkins 130 times": ["Pumpkin Harvested", 130],
  "Harvest Pumpkins 150 times": ["Pumpkin Harvested", 150],
  "Harvest Pumpkins 200 times": ["Pumpkin Harvested", 200],
  "Harvest Pumpkins 250 times": ["Pumpkin Harvested", 250],
  "Harvest Zucchini 50 times": ["Zucchini Harvested", 50],
  "Harvest Zucchini 75 times": ["Zucchini Harvested", 75],
  "Harvest Zucchini 100 times": ["Zucchini Harvested", 100],
  "Harvest Zucchini 125 times": ["Zucchini Harvested", 125],
  "Harvest Zucchini 150 times": ["Zucchini Harvested", 150],
  "Harvest Zucchini 175 times": ["Zucchini Harvested", 175],
  "Harvest Carrots 50 times": ["Carrot Harvested", 50],
  "Harvest Carrots 60 times": ["Carrot Harvested", 60],
  "Harvest Carrots 75 times": ["Carrot Harvested", 75],
  "Harvest Carrots 100 times": ["Carrot Harvested", 100],
  "Harvest Carrots 120 times": ["Carrot Harvested", 120],
  "Harvest Carrots 125 times": ["Carrot Harvested", 125],
  "Harvest Carrots 130 times": ["Carrot Harvested", 130],
  "Harvest Carrots 150 times": ["Carrot Harvested", 150],
  "Harvest Carrots 170 times": ["Carrot Harvested", 170],
  "Harvest Carrots 175 times": ["Carrot Harvested", 175],
  "Harvest Carrots 200 times": ["Carrot Harvested", 200],
  "Harvest Yam 30 times": ["Yam Harvested", 30],
  "Harvest Yam 60 times": ["Yam Harvested", 60],
  "Harvest Yam 90 times": ["Yam Harvested", 90],
  "Harvest Yam 125 times": ["Yam Harvested", 125],
  "Harvest Yam 150 times": ["Yam Harvested", 150],
  "Harvest Yam 175 times": ["Yam Harvested", 175],
  "Harvest Yam 200 times": ["Yam Harvested", 200],
  "Harvest Yam 225 times": ["Yam Harvested", 225],
  "Harvest Yam 250 times": ["Yam Harvested", 250],
  "Harvest Yam 275 times": ["Yam Harvested", 275],
  "Harvest Cabbage 25 times": ["Cabbage Harvested", 25],
  "Harvest Cabbage 30 times": ["Cabbage Harvested", 30],
  "Harvest Cabbage 40 times": ["Cabbage Harvested", 40],
  "Harvest Cabbage 50 times": ["Cabbage Harvested", 50],
  "Harvest Cabbage 60 times": ["Cabbage Harvested", 60],
  "Harvest Cabbage 75 times": ["Cabbage Harvested", 75],
  "Harvest Cabbage 80 times": ["Cabbage Harvested", 80],
  "Harvest Cabbage 90 times": ["Cabbage Harvested", 90],
  "Harvest Cabbage 100 times": ["Cabbage Harvested", 100],
  "Harvest Cabbage 125 times": ["Cabbage Harvested", 125],
  "Harvest Cabbage 150 times": ["Cabbage Harvested", 150],
  "Harvest Cabbage 175 times": ["Cabbage Harvested", 175],
  "Harvest Cabbage 200 times": ["Cabbage Harvested", 200],
  "Harvest Cabbage 220 times": ["Cabbage Harvested", 220],
  "Harvest Broccoli 40 times": ["Broccoli Harvested", 40],
  "Harvest Broccoli 80 times": ["Broccoli Harvested", 80],
  "Harvest Broccoli 100 times": ["Broccoli Harvested", 100],
  "Harvest Broccoli 125 times": ["Broccoli Harvested", 125],
  "Harvest Broccoli 150 times": ["Broccoli Harvested", 150],
  "Harvest Broccoli 175 times": ["Broccoli Harvested", 175],
  "Harvest Soybeans 30 times": ["Soybean Harvested", 30],
  "Harvest Soybeans 60 times": ["Soybean Harvested", 60],
  "Harvest Soybeans 90 times": ["Soybean Harvested", 90],
  "Harvest Soybeans 75 times": ["Soybean Harvested", 75],
  "Harvest Soybeans 100 times": ["Soybean Harvested", 100],
  "Harvest Soybeans 125 times": ["Soybean Harvested", 125],
  "Harvest Soybeans 150 times": ["Soybean Harvested", 150],
  "Harvest Beetroot 30 times": ["Beetroot Harvested", 30],
  "Harvest Beetroot 50 times": ["Beetroot Harvested", 50],
  "Harvest Beetroot 60 times": ["Beetroot Harvested", 60],
  "Harvest Beetroot 75 times": ["Beetroot Harvested", 75],
  "Harvest Beetroot 90 times": ["Beetroot Harvested", 90],
  "Harvest Beetroot 100 times": ["Beetroot Harvested", 100],
  "Harvest Beetroot 120 times": ["Beetroot Harvested", 120],
  "Harvest Beetroot 125 times": ["Beetroot Harvested", 125],
  "Harvest Beetroot 150 times": ["Beetroot Harvested", 150],
  "Harvest Beetroot 175 times": ["Beetroot Harvested", 175],
  "Harvest Beetroots 125 times": ["Beetroot Harvested", 125],
  "Harvest Beetroots 150 times": ["Beetroot Harvested", 150],
  "Harvest Beetroots 200 times": ["Beetroot Harvested", 200],
  "Harvest Beetroots 220 times": ["Beetroot Harvested", 220],
  "Harvest Pepper 25 times": ["Pepper Harvested", 25],
  "Harvest Pepper 40 times": ["Pepper Harvested", 40],
  "Harvest Pepper 50 times": ["Pepper Harvested", 50],
  "Harvest Pepper 75 times": ["Pepper Harvested", 75],
  "Harvest Pepper 80 times": ["Pepper Harvested", 80],
  "Harvest Pepper 100 times": ["Pepper Harvested", 100],
  "Harvest Pepper 125 times": ["Pepper Harvested", 125],
  "Harvest Pepper 150 times": ["Pepper Harvested", 150],
  "Harvest Cauliflower 30 times": ["Cauliflower Harvested", 30],
  "Harvest Cauliflower 60 times": ["Cauliflower Harvested", 60],
  "Harvest Cauliflower 90 times": ["Cauliflower Harvested", 90],
  "Harvest Cauliflower 400 times": ["Cauliflower Harvested", 400],
  "Harvest Cauliflower 450 times": ["Cauliflower Harvested", 450],
  "Harvest Cauliflower 500 times": ["Cauliflower Harvested", 500],
  "Harvest Cauliflowers 75 times": ["Cauliflower Harvested", 75],
  "Harvest Cauliflowers 100 times": ["Cauliflower Harvested", 100],
  "Harvest Cauliflowers 125 times": ["Cauliflower Harvested", 125],
  "Harvest Cauliflowers 150 times": ["Cauliflower Harvested", 150],
  "Harvest Cauliflowers 175 times": ["Cauliflower Harvested", 175],
  "Harvest Parsnips 50 times": ["Parsnip Harvested", 50],
  "Harvest Parsnips 75 times": ["Parsnip Harvested", 75],
  "Harvest Parsnips 100 times": ["Parsnip Harvested", 100],
  "Harvest Parsnips 125 times": ["Parsnip Harvested", 125],
  "Harvest Eggplant 300 times": ["Eggplant Harvested", 300],
  "Harvest Eggplant 360 times": ["Eggplant Harvested", 360],
  "Harvest Eggplant 420 times": ["Eggplant Harvested", 420],
  "Harvest Eggplant 480 times": ["Eggplant Harvested", 480],
  "Harvest Corn 50 times": ["Corn Harvested", 50],
  "Harvest Corn 100 times": ["Corn Harvested", 100],
  "Harvest Corn 125 times": ["Corn Harvested", 125],
  "Harvest Corn 150 times": ["Corn Harvested", 150],
  "Harvest Corn 300 times": ["Corn Harvested", 300],
  "Harvest Corn 350 times": ["Corn Harvested", 350],
  "Harvest Corn 360 times": ["Corn Harvested", 360],
  "Harvest Corn 400 times": ["Corn Harvested", 400],
  "Harvest Corn 420 times": ["Corn Harvested", 420],
  "Harvest Corn 450 times": ["Corn Harvested", 450],
  "Harvest Onion 360 times": ["Onion Harvested", 360],
  "Harvest Onion 420 times": ["Onion Harvested", 420],
  "Harvest Onion 460 times": ["Onion Harvested", 460],
  "Harvest Onions 300 times": ["Onion Harvested", 300],
  "Harvest Onions 360 times": ["Onion Harvested", 360],
  "Harvest Onions 420 times": ["Onion Harvested", 420],
  "Harvest Wheat 240 times": ["Wheat Harvested", 240],
  "Harvest Wheat 250 times": ["Wheat Harvested", 250],
  "Harvest Wheat 275 times": ["Wheat Harvested", 275],
  "Harvest Wheat 300 times": ["Wheat Harvested", 300],
  "Harvest Wheat 325 times": ["Wheat Harvested", 325],
  "Harvest Wheat 350 times": ["Wheat Harvested", 350],
  "Harvest Wheat 360 times": ["Wheat Harvested", 360],
  "Harvest Wheat 400 times": ["Wheat Harvested", 400],
  "Harvest Wheat 420 times": ["Wheat Harvested", 420],
  "Harvest Radish 240 times": ["Radish Harvested", 240],
  "Harvest Radish 275 times": ["Radish Harvested", 275],
  "Harvest Radish 280 times": ["Radish Harvested", 280],
  "Harvest Radish 325 times": ["Radish Harvested", 325],
  "Harvest Radish 340 times": ["Radish Harvested", 340],
  "Harvest Radish 400 times": ["Radish Harvested", 400],
  "Harvest Turnip 250 times": ["Turnip Harvested", 250],
  "Harvest Turnip 300 times": ["Turnip Harvested", 300],
  "Harvest Turnip 350 times": ["Turnip Harvested", 350],
  "Harvest Turnip 360 times": ["Turnip Harvested", 360],
  "Harvest Turnip 400 times": ["Turnip Harvested", 400],
  "Harvest Kale 120 times": ["Kale Harvested", 120],
  "Harvest Kale 150 times": ["Kale Harvested", 150],
  "Harvest Kale 180 times": ["Kale Harvested", 180],
  "Harvest Kale 200 times": ["Kale Harvested", 200],
  "Harvest Kale 220 times": ["Kale Harvested", 220],
  "Harvest Kale 240 times": ["Kale Harvested", 240],
  "Harvest Kale 250 times": ["Kale Harvested", 250],
  "Harvest Kale 300 times": ["Kale Harvested", 300],
  "Harvest Artichoke 150 times": ["Artichoke Harvested", 150],
  "Harvest Artichoke 200 times": ["Artichoke Harvested", 200],
  "Harvest Artichoke 250 times": ["Artichoke Harvested", 250],
  "Harvest Artichoke 260 times": ["Artichoke Harvested", 260],
  "Harvest Artichoke 300 times": ["Artichoke Harvested", 300],
  "Harvest Barley 100 times": ["Barley Harvested", 100],
  "Harvest Barley 120 times": ["Barley Harvested", 120],
  "Harvest Barley 125 times": ["Barley Harvested", 125],
  "Harvest Barley 150 times": ["Barley Harvested", 150],
  "Harvest Barley 175 times": ["Barley Harvested", 175],
  "Harvest Barley 180 times": ["Barley Harvested", 180],
  "Harvest Barley 200 times": ["Barley Harvested", 200],
  "Harvest Barley 250 times": ["Barley Harvested", 250],
  "Harvest Rice 16 times": ["Rice Harvested", 16],
  "Harvest Rice 20 times": ["Rice Harvested", 20],
  "Harvest Rice 24 times": ["Rice Harvested", 24],
  "Harvest Rice 28 times": ["Rice Harvested", 28],
  "Harvest Olives 12 times": ["Olive Harvested", 12],
  "Harvest Olives 16 times": ["Olive Harvested", 16],
  "Harvest Olives 20 times": ["Olive Harvested", 20],
  "Harvest Olives 24 times": ["Olive Harvested", 24],
  "Eat 3 Boiled Eggs": ["Boiled Eggs Fed", 3],
  "Eat 5 Boiled Eggs": ["Boiled Eggs Fed", 5],
  "Eat 7 Boiled Eggs": ["Boiled Eggs Fed", 7],
  "Eat 10 Boiled Eggs": ["Boiled Eggs Fed", 10],
  "Eat 15 Boiled Eggs": ["Boiled Eggs Fed", 15],
  "Eat 10 Reindeer Carrot": ["Reindeer Carrot Fed", 10],
  "Eat 15 Reindeer Carrot": ["Reindeer Carrot Fed", 15],
  "Eat 20 Anchovies": ["Anchovy Fed", 20],
  "Eat 35 Anchovies": ["Anchovy Fed", 35],
  "Eat 40 Anchovies": ["Anchovy Fed", 40],
  "Eat 50 Anchovies": ["Anchovy Fed", 50],
  "Eat 60 Anchovies": ["Anchovy Fed", 60],
  "Eat 65 Anchovies": ["Anchovy Fed", 65],
  "Eat 10 Tunas": ["Tuna Fed", 10],
  "Eat 20 Tunas": ["Tuna Fed", 20],
  "Eat 25 Tunas": ["Tuna Fed", 25],
  "Eat 30 Tunas": ["Tuna Fed", 30],
  "Eat 50 Tunas": ["Tuna Fed", 50],
  "Eat 75 Tunas": ["Tuna Fed", 75],
  "Eat 15 Red Snappers": ["Red Snapper Fed", 15],
  "Eat 30 Red Snappers": ["Red Snapper Fed", 30],
  "Eat 45 Red Snappers": ["Red Snapper Fed", 45],
  "Eat 5 Cauliflower Burgers": ["Cauliflower Burger Fed", 5],
  "Eat 5 Club Sandwiches": ["Club Sandwich Fed", 5],
  "Eat 5 Pancakes": ["Pancakes Fed", 5],
  "Eat 20 Chowder": ["Chowder Fed", 20],
  "Eat 25 Chowder": ["Chowder Fed", 25],
  "Eat 30 Chowder": ["Chowder Fed", 30],
  "Eat 5 Orange Cake": ["Orange Cake Fed", 5],
  "Eat 7 Orange Cake": ["Orange Cake Fed", 7],
  "Eat 10 Orange Cake": ["Orange Cake Fed", 10],
  "Eat 13 Orange Cake": ["Orange Cake Fed", 13],
  "Eat 15 Orange Cake": ["Orange Cake Fed", 15],
  "Eat 16 Orange Cake": ["Orange Cake Fed", 16],
  "Eat 20 Orange Cake": ["Orange Cake Fed", 20],
  "Eat 10 Mashed Potatoes": ["Mashed Potato Fed", 10],
  "Eat 15 Mashed Potatoes": ["Mashed Potato Fed", 15],
  "Eat 20 Mashed Potatoes": ["Mashed Potato Fed", 20],
  "Eat 30 Mashed Potatoes": ["Mashed Potato Fed", 30],
  "Eat 20 Pumpkin Soup": ["Pumpkin Soup Fed", 20],
  "Eat 30 Pumpkin Soup": ["Pumpkin Soup Fed", 30],
  "Eat 5 Bumpkin Salad": ["Bumpkin Salad Fed", 5],
  "Drink 15 Orange Juice": ["Orange Juice Fed", 15],
  "Drink 15 Purple Smoothies": ["Purple Smoothie Fed", 15],
  "Drink Purple Smoothies 15 times": ["Purple Smoothie Fed", 15],
  "Drink Purple Smoothies 20 times": ["Purple Smoothie Fed", 20],
  "Drink 10 Apple Juice": ["Apple Juice Fed", 10],
  "Drink Apple Juice 10 times": ["Apple Juice Fed", 10],
  "Drink Apple Juice 15 times": ["Apple Juice Fed", 15],
  "Drink 5 Power Smoothies": ["Power Smoothie Fed", 5],
  "Drink 25 Orange Juice": ["Orange Juice Fed", 25],
  "Drink 35 Orange Juice": ["Orange Juice Fed", 35],
  "Drink 40 Orange Juice": ["Orange Juice Fed", 40],
  "Drink 50 Orange Juice": ["Orange Juice Fed", 50],
  "Drink 45 Orange Juice": ["Orange Juice Fed", 45],
  "Drink 55 Orange Juice": ["Orange Juice Fed", 55],
  "Drink Orange Juice 15 times": ["Orange Juice Fed", 15],
  "Drink Orange Juice 20 times": ["Orange Juice Fed", 20],
  "Drink 15 Sour Shakes": ["Sour Shake Fed", 15],
  "Drink 15 Banana Blast": ["Banana Blast Fed", 15],
  "Drink 5 Grape Juice": ["Grape Juice Fed", 5],
  "Drink 10 Orange Juice": ["Orange Juice Fed", 10],
  "Drink 15 Carrot Juice": ["Carrot Juice Fed", 15],
  "Cook Boiled Eggs 3 times": ["Boiled Eggs Cooked", 3],
  "Cook Boiled Eggs 5 times": ["Boiled Eggs Cooked", 5],
  "Cook Boiled Eggs 10 times": ["Boiled Eggs Cooked", 10],
  "Cook Boiled Eggs 15 times": ["Boiled Eggs Cooked", 15],
  "Cook Boiled Eggs 25 times": ["Boiled Eggs Cooked", 25],
  "Cook Reindeer Carrot 8 times": ["Reindeer Carrot Cooked", 8],
  "Cook Reindeer Carrot 12 times": ["Reindeer Carrot Cooked", 12],
  "Cook Reindeer Carrot 20 times": ["Reindeer Carrot Cooked", 20],
  "Cook Reindeer Carrot 25 times": ["Reindeer Carrot Cooked", 25],
  "Cook Mashed Potatoes 15 times": ["Mashed Potato Cooked", 15],
  "Cook Mashed Potatoes 18 times": ["Mashed Potato Cooked", 18],
  "Cook Mashed Potatoes 20 times": ["Mashed Potato Cooked", 20],
  "Cook Mashed Potatoes 50 times": ["Mashed Potato Cooked", 50],
  "Cook Mashed Potatoes 65 times": ["Mashed Potato Cooked", 65],
  "Cook Roast Veggies 5 times": ["Roast Veggies Cooked", 5],
  "Cook Roast Veggies 6 times": ["Roast Veggies Cooked", 6],
  "Cook Roast Veggies 7 times": ["Roast Veggies Cooked", 7],
  "Cook Club Sandwich 5 times": ["Club Sandwich Cooked", 5],
  "Cook Club Sandwich 6 times": ["Club Sandwich Cooked", 6],
  "Cook Club Sandwich 7 times": ["Club Sandwich Cooked", 7],
  "Cook Pancakes 3 times": ["Pancakes Cooked", 3],
  "Cook Pancakes 4 times": ["Pancakes Cooked", 4],
  "Cook Pancakes 5 times": ["Pancakes Cooked", 5],
  "Cook Pancakes 6 times": ["Pancakes Cooked", 6],
  "Cook Pancakes 7 times": ["Pancakes Cooked", 7],
  "Cook Pancakes 10 times": ["Pancakes Cooked", 10],
  "Cook Pancakes 12 times": ["Pancakes Cooked", 12],
  "Cook Pancakes 15 times": ["Pancakes Cooked", 15],
  "Cook Pancakes 17 times": ["Pancakes Cooked", 17],
  "Cook Pancakes 20 times": ["Pancakes Cooked", 20],
  "Cook Pancakes 22 times": ["Pancakes Cooked", 22],
  "Cook Pancakes 25 times": ["Pancakes Cooked", 25],
  "Cook Fried Calamari 1 time": ["Fried Calamari Cooked", 1],
  "Cook Fried Calamari 2 times": ["Fried Calamari Cooked", 2],
  "Cook Fried Calamari 3 times": ["Fried Calamari Cooked", 3],
  "Cook Fried Calamari 4 times": ["Fried Calamari Cooked", 4],
  "Cook Fried Calamari 5 times": ["Fried Calamari Cooked", 5],
  "Cook Cauliflower Burger 5 times": ["Cauliflower Burger Cooked", 5],
  "Cook Cauliflower Burger 7 times": ["Cauliflower Burger Cooked", 7],
  "Cook Cauliflower Burger 10 times": ["Cauliflower Burger Cooked", 10],
  "Cook Cauliflower Burger 15 times": ["Cauliflower Burger Cooked", 15],
  "Cook Cauliflower Burger 17 times": ["Cauliflower Burger Cooked", 17],
  "Cook Cauliflower Burger 20 times": ["Cauliflower Burger Cooked", 20],
  "Cook Cauliflower Burger 25 times": ["Cauliflower Burger Cooked", 25],
  "Cook Cauliflower Burger 30 times": ["Cauliflower Burger Cooked", 30],
  "Cook Cauliflower Burger 35 times": ["Cauliflower Burger Cooked", 35],
  "Cook Bumpkin Salad 5 times": ["Bumpkin Salad Cooked", 5],
  "Cook Bumpkin Salad 7 times": ["Bumpkin Salad Cooked", 7],
  "Cook Bumpkin Salad 10 times": ["Bumpkin Salad Cooked", 10],
  "Cook Bumpkin Salad 15 times": ["Bumpkin Salad Cooked", 15],
  "Cook Bumpkin Salad 17 times": ["Bumpkin Salad Cooked", 17],
  "Cook Bumpkin Salad 20 times": ["Bumpkin Salad Cooked", 20],
  "Cook Bumpkin ganoush 3 times": ["Bumpkin ganoush Cooked", 3],
  "Cook Bumpkin ganoush 5 times": ["Bumpkin ganoush Cooked", 5],
  "Cook Bumpkin ganoush 7 times": ["Bumpkin ganoush Cooked", 7],
  "Cook Bumpkin ganoush 10 times": ["Bumpkin ganoush Cooked", 10],
  "Cook Bumpkin ganoush 12 times": ["Bumpkin ganoush Cooked", 12],
  "Cook Bumpkin ganoush 15 times": ["Bumpkin ganoush Cooked", 15],
  "Cook Bumpkin ganoush 20 times": ["Bumpkin ganoush Cooked", 20],
  "Cook Goblin's Treat 3 times": ["Goblin's Treat Cooked", 3],
  "Cook Goblin's Treat 5 times": ["Goblin's Treat Cooked", 5],
  "Cook Goblin's Treat 7 times": ["Goblin's Treat Cooked", 7],
  "Cook Goblin's Treat 10 times": ["Goblin's Treat Cooked", 10],
  "Cook Goblin's Treat 12 times": ["Goblin's Treat Cooked", 12],
  "Cook Gumbo 20 times": ["Gumbo Cooked", 20],
  "Cook Gumbo 25 times": ["Gumbo Cooked", 25],
  "Cook Gumbo 30 times": ["Gumbo Cooked", 30],
  "Cook Gumbo 45 times": ["Gumbo Cooked", 45],
  "Cook Gumbo 60 times": ["Gumbo Cooked", 60],
  "Cook Gumbo 35 times": ["Gumbo Cooked", 35],
  "Cook Gumbo 50 times": ["Gumbo Cooked", 50],
  "Cook Sunflower Cake 7 times": ["Sunflower Cake Cooked", 7],
  "Cook 10 Sunflower Cakes": ["Sunflower Cake Cooked", 10],
  "Cook 15 Sunflower Cakes": ["Sunflower Cake Cooked", 15],
  "Cook Sunflower Cakes 10 times": ["Sunflower Cake Cooked", 10],
  "Cook Sunflower Cakes 15 times": ["Sunflower Cake Cooked", 15],
  "Cook Carrot Cake 5 times": ["Carrot Cake Cooked", 5],
  "Cook 7 Carrot Cakes": ["Carrot Cake Cooked", 7],
  "Cook 10 Carrot Cakes": ["Carrot Cake Cooked", 10],
  "Cook Cabbage Cake 5 times": ["Cabbage Cake Cooked", 5],
  "Cook 7 Cabbage Cakes": ["Cabbage Cake Cooked", 7],
  "Cook 10 Cabbage Cakes": ["Cabbage Cake Cooked", 10],
  "Cook Wheat Cake 5 times": ["Wheat Cake Cooked", 5],
  "Cook Honey Cake 10 times": ["Honey Cake Cooked", 10],
  "Cook Honey Cake 15 times": ["Honey Cake Cooked", 15],
  "Cook Honey Cake 20 times": ["Honey Cake Cooked", 20],
  "Cook Cornbread 10 times": ["Cornbread Cooked", 10],
  "Cook Cornbread 15 times": ["Cornbread Cooked", 15],
  "Cook Lemon Cheesecakes 3 times": ["Lemon Cheesecake Cooked", 3],
  "Cook Lemon Cheesecakes 5 times": ["Lemon Cheesecake Cooked", 5],
  "Cook Wheat Cakes 7 times": ["Wheat Cake Cooked", 7],
  "Cook Wheat Cakes 10 times": ["Wheat Cake Cooked", 10],
  "Cook Wheat Cakes 5 times": ["Wheat Cake Cooked", 5],
  "Cook Honey Cakes 10 times": ["Honey Cake Cooked", 10],
  "Cook Honey Cakes 15 times": ["Honey Cake Cooked", 15],
  "Cook Honey Cakes 20 times": ["Honey Cake Cooked", 20],
  "Cook Fermented Fish 10 times": ["Fermented Fish Cooked", 10],
  "Cook Fermented Fish 12 times": ["Fermented Fish Cooked", 12],
  "Cook Fermented Fish 15 times": ["Fermented Fish Cooked", 15],
  "Cook Fermented Fish 20 times": ["Fermented Fish Cooked", 20],
  "Cook Fermented Fish 25 times": ["Fermented Fish Cooked", 25],
  "Cook Fermented Fish 30 times": ["Fermented Fish Cooked", 30],
  "Cook Fermented Fish 35 times": ["Fermented Fish Cooked", 35],
  "Cook Chowder 15 times": ["Chowder Cooked", 15],
  "Cook Chowder 18 times": ["Chowder Cooked", 18],
  "Cook Chowder 21 times": ["Chowder Cooked", 21],
  "Cook 20 Chowder times": ["Chowder Cooked", 20],
  "Cook 25 Chowder times": ["Chowder Cooked", 25],
  "Cook 30 Chowder times": ["Chowder Cooked", 30],
  "Cook 35 Chowder times": ["Chowder Cooked", 35],
  "Cook 50 Chowder times": ["Chowder Cooked", 50],
  "Cook Antipasto 25 times": ["Antipasto Cooked", 25],
  "Cook Antipasto 30 times": ["Antipasto Cooked", 30],
  "Cook Antipasto 35 times": ["Antipasto Cooked", 35],
  "Cook Antipasto 40 times": ["Antipasto Cooked", 40],
  "Cook Antipasto 45 times": ["Antipasto Cooked", 45],
  "Cook Antipasto 50 times": ["Antipasto Cooked", 50],
  "Cook Fruit Salad 50 times": ["Fruit Salad Cooked", 50],
  "Cook Fruit Salad 75 times": ["Fruit Salad Cooked", 75],
  "Cook Fruit Salad 100 times": ["Fruit Salad Cooked", 100],
  "Cook Steamed Red Rice 10 times": ["Steamed Red Rice Cooked", 10],
  "Cook Steamed Red Rice 12 times": ["Steamed Red Rice Cooked", 12],
  "Cook Steamed Red Rice 13 times": ["Steamed Red Rice Cooked", 13],
  "Cook Steamed Red Rice 15 times": ["Steamed Red Rice Cooked", 15],
  "Cook Steamed Red Rice 16 times": ["Steamed Red Rice Cooked", 16],
  "Cook Steamed Red Rice 18 times": ["Steamed Red Rice Cooked", 18],
  "Cook Steamed Red Rice 20 times": ["Steamed Red Rice Cooked", 20],
  "Cook Steamed Red Rice 25 times": ["Steamed Red Rice Cooked", 25],
  "Cook Steamed Red Rice 30 times": ["Steamed Red Rice Cooked", 30],
  "Cook Rice Bun 20 times": ["Rice Bun Cooked", 20],
  "Cook Rice Bun 25 times": ["Rice Bun Cooked", 25],
  "Cook Rice Bun 30 times": ["Rice Bun Cooked", 30],
  "Cook Rice Bun 35 times": ["Rice Bun Cooked", 35],
  "Cook Rice Bun 40 times": ["Rice Bun Cooked", 40],
  "Cook Rice Bun 45 times": ["Rice Bun Cooked", 45],
  "Cook Shroom Syrup 2 times": ["Shroom Syrup Cooked", 2],
  "Cook Cheese 50 times": ["Cheese Cooked", 50],
  "Cook Cheese 75 times": ["Cheese Cooked", 75],
  "Cook Cheese 85 times": ["Cheese Cooked", 85],
  "Cook Cheese 100 times": ["Cheese Cooked", 100],
  "Cook Honey Cheddar 5 times": ["Honey Cheddar Cooked", 5],
  "Cook Honey Cheddar 7 times": ["Honey Cheddar Cooked", 7],
  "Cook Honey Cheddar 10 times": ["Honey Cheddar Cooked", 10],
  "Cook Honey Cheddar 12 times": ["Honey Cheddar Cooked", 12],
  "Cook Honey Cheddar 15 times": ["Honey Cheddar Cooked", 15],
  "Cook Honey Cheddar 17 times": ["Honey Cheddar Cooked", 17],
  "Cook Honey Cheddar 20 times": ["Honey Cheddar Cooked", 20],
  "Cook Blue Cheese 20 times": ["Blue Cheese Cooked", 20],
  "Cook Blue Cheese 25 times": ["Blue Cheese Cooked", 25],
  "Cook Blue Cheese 30 times": ["Blue Cheese Cooked", 30],
  "Cook Blue Cheese 33 times": ["Blue Cheese Cooked", 33],
  "Cook Blue Cheese 35 times": ["Blue Cheese Cooked", 35],
  "Cook Blue Cheese 40 times": ["Blue Cheese Cooked", 40],
  "Cook Blue Cheese 45 times": ["Blue Cheese Cooked", 45],
  "Cook Blue Cheese 50 times": ["Blue Cheese Cooked", 50],
  "Cook Blue Cheese 60 times": ["Blue Cheese Cooked", 60],
  "Cook Goblin Brunch 1 time": ["Goblin Brunch Cooked", 1],
  "Cook Goblin Brunch 2 times": ["Goblin Brunch Cooked", 2],
  "Cook Goblin Brunch 3 times": ["Goblin Brunch Cooked", 3],
  "Cook Goblin Brunch 4 times": ["Goblin Brunch Cooked", 4],
  "Cook Goblin Brunch 5 times": ["Goblin Brunch Cooked", 5],
  "Cook Goblin Brunch 12 times": ["Goblin Brunch Cooked", 12],
  "Cook Goblin Brunch 15 times": ["Goblin Brunch Cooked", 15],
  "Cook Goblin Brunch 18 times": ["Goblin Brunch Cooked", 18],
  "Cook Sushi Roll 3 times": ["Sushi Roll Cooked", 3],
  "Cook Sushi Roll 4 times": ["Sushi Roll Cooked", 4],
  "Cook Sushi Roll 5 times": ["Sushi Roll Cooked", 5],
  "Cook Sushi Roll 7 times": ["Sushi Roll Cooked", 7],
  "Cook Sushi Roll 10 times": ["Sushi Roll Cooked", 10],
  "Cook Sushi Roll 12 times": ["Sushi Roll Cooked", 12],
  "Cook Caprese Salad 4 times": ["Caprese Salad Cooked", 4],
  "Cook Caprese Salad 5 times": ["Caprese Salad Cooked", 5],
  "Cook Caprese Salad 6 times": ["Caprese Salad Cooked", 6],
  "Cook Caprese Salad 7 times": ["Caprese Salad Cooked", 7],
  "Cook Caprese Salad 8 times": ["Caprese Salad Cooked", 8],
  "Cook Caprese Salad 10 times": ["Caprese Salad Cooked", 10],
  "Cook Caprese Salad 12 times": ["Caprese Salad Cooked", 12],
  "Cook Caprese Salad 15 times": ["Caprese Salad Cooked", 15],
  "Cook Ocean's Olive 3 times": ["Ocean's Olive Cooked", 3],
  "Cook Ocean's Olive 5 times": ["Ocean's Olive Cooked", 5],
  "Cook Ocean's Olive 7 times": ["Ocean's Olive Cooked", 7],
  "Cook Ocean's Olive 10 times": ["Ocean's Olive Cooked", 10],
  "Cook Ocean's Olive 12 times": ["Ocean's Olive Cooked", 12],
  "Cook Eggplant Cake 5 times": ["Eggplant Cake Cooked", 5],
  "Cook Eggplant Cakes 5 times": ["Eggplant Cake Cooked", 5],
  "Cook Eggplant Cakes 10 times": ["Eggplant Cake Cooked", 10],
  "Cook Radish Cake 5 times": ["Radish Cake Cooked", 5],
  "Cook Radish Cakes 5 times": ["Radish Cake Cooked", 5],
  "Cook Radish Cakes 10 times": ["Radish Cake Cooked", 10],
  "Cook Beetroot Cake 5 times": ["Beetroot Cake Cooked", 5],
  "Cook Beetroot Cakes 5 times": ["Beetroot Cake Cooked", 5],
  "Cook Beetroot Cakes 10 times": ["Beetroot Cake Cooked", 10],
  "Cook Pumpkin Soup 5 times": ["Pumpkin Soup Cooked", 5],
  "Cook Pumpkin Soup 7 times": ["Pumpkin Soup Cooked", 7],
  "Cook Pumpkin Soup 10 times": ["Pumpkin Soup Cooked", 10],
  "Cook Bumpkin Roast 5 times": ["Bumpkin Roast Cooked", 5],
  "Cook Bumpkin Roast 7 times": ["Bumpkin Roast Cooked", 7],
  "Cook Bumpkin Roast 10 times": ["Bumpkin Roast Cooked", 10],
  "Cook Bumpkin Roast 12 times": ["Bumpkin Roast Cooked", 12],
  "Cook Bumpkin Roast 15 times": ["Bumpkin Roast Cooked", 15],
  "Cook Pizza Margherita 5 times": ["Pizza Margherita Cooked", 5],
  "Cook Pizza Margherita 7 times": ["Pizza Margherita Cooked", 7],
  "Cook Pizza Margherita 10 times": ["Pizza Margherita Cooked", 10],
  "Cook Pizza Margherita 12 times": ["Pizza Margherita Cooked", 12],
  "Cook Apple Pie 15 times": ["Apple Pie Cooked", 15],
  "Cook Apple Pie 20 times": ["Apple Pie Cooked", 20],
  "Cook Potato Cake 7 times": ["Potato Cake Cooked", 7],
  "Cook Potato Cakes 7 times": ["Potato Cake Cooked", 7],
  "Cook Potato Cakes 10 times": ["Potato Cake Cooked", 10],
  "Cook Carrot Cake 7 times": ["Carrot Cake Cooked", 7],
  "Cook Carrot Cakes 7 times": ["Carrot Cake Cooked", 7],
  "Cook Carrot Cakes 10 times": ["Carrot Cake Cooked", 10],
  "Cook Wheat Cake 7 times": ["Wheat Cake Cooked", 7],
  "Cook Spaghetti al Limone 4 times": ["Spaghetti al Limone Cooked", 4],
  "Cook Spaghetti al Limone 6 times": ["Spaghetti al Limone Cooked", 6],
  "Cook Spaghetti al Limone 7 times": ["Spaghetti al Limone Cooked", 7],
  "Cook Spaghetti al Limone 8 times": ["Spaghetti al Limone Cooked", 8],
  "Cook Spaghetti al Limone 10 times": ["Spaghetti al Limone Cooked", 10],
  "Cook Spaghetti al Limone 12 times": ["Spaghetti al Limone Cooked", 12],
  "Cook Beetroot Cake 7 times": ["Beetroot Cake Cooked", 7],
  "Cook Beetroot Cakes 7 times": ["Beetroot Cake Cooked", 7],
  "Cook Cabbage Cake 7 times": ["Cabbage Cake Cooked", 7],
  "Cook Cabbage Cakes 7 times": ["Cabbage Cake Cooked", 7],
  "Cook Cabbage Cakes 10 times": ["Cabbage Cake Cooked", 10],
  "Cook Parsnip Cake 7 times": ["Parsnip Cake Cooked", 7],
  "Cook Parsnip Cakes 7 times": ["Parsnip Cake Cooked", 7],
  "Cook Parsnip Cakes 10 times": ["Parsnip Cake Cooked", 10],
  "Cook Cauliflower Cake 7 times": ["Cauliflower Cake Cooked", 7],
  "Cook Cauliflower Cakes 7 times": ["Cauliflower Cake Cooked", 7],
  "Cook Cauliflower Cakes 10 times": ["Cauliflower Cake Cooked", 10],
  "Prepare Power Smoothie 10 times": ["Power Smoothie Cooked", 10],
  "Prepare Power Smoothie 12 times": ["Power Smoothie Cooked", 12],
  "Prepare Power Smoothie 15 times": ["Power Smoothie Cooked", 15],
  "Prepare Power Smoothie 20 times": ["Power Smoothie Cooked", 20],
  "Prepare Power Smoothie 25 times": ["Power Smoothie Cooked", 25],
  "Prepare Power Smoothie 30 times": ["Power Smoothie Cooked", 30],
  "Prepare Power Smoothie 35 times": ["Power Smoothie Cooked", 35],
  "Prepare Power Smoothie 45 times": ["Power Smoothie Cooked", 45],
  "Prepare Power Smoothie 50 times": ["Power Smoothie Cooked", 50],
  "Prepare Power Smoothie 60 times": ["Power Smoothie Cooked", 60],
  "Prepare Slow Juice 5 times": ["Slow Juice Cooked", 5],
  "Prepare Slow Juice 6 times": ["Slow Juice Cooked", 6],
  "Prepare Slow Juice 7 times": ["Slow Juice Cooked", 7],
  "Prepare Slow Juice 10 times": ["Slow Juice Cooked", 10],
  "Prepare Slow Juice 12 times": ["Slow Juice Cooked", 12],
  "Prepare Slow Juice 15 times": ["Slow Juice Cooked", 15],
  "Prepare Banana Blast 15 times": ["Banana Blast Cooked", 15],
  "Prepare Banana Blast 17 times": ["Banana Blast Cooked", 17],
  "Prepare Banana Blast 20 times": ["Banana Blast Cooked", 20],
  "Prepare Banana Blast 35 times": ["Banana Blast Cooked", 35],
  "Prepare Banana Blast 50 times": ["Banana Blast Cooked", 50],
  "Prepare Grape Juice 5 times": ["Grape Juice Cooked", 5],
  "Prepare Grape Juice 10 times": ["Grape Juice Cooked", 10],
  "Prepare Grape Juice 12 times": ["Grape Juice Cooked", 12],
  "Prepare Grape Juice 15 times": ["Grape Juice Cooked", 15],
  "Prepare Apple Juice 5 times": ["Apple Juice Cooked", 5],
  "Prepare Apple Juice 6 times": ["Apple Juice Cooked", 6],
  "Prepare Apple Juice 7 times": ["Apple Juice Cooked", 7],
  "Cook Apple Juice 10 times": ["Apple Juice Cooked", 10],
  "Cook Apple Juice 12 times": ["Apple Juice Cooked", 12],
  "Cook Apple Juice 15 times": ["Apple Juice Cooked", 15],
  "Prepare Apple Juice 10 times": ["Apple Juice Cooked", 10],
  "Prepare Apple Juice 12 times": ["Apple Juice Cooked", 12],
  "Prepare Apple Juice 15 times": ["Apple Juice Cooked", 15],
  "Prepare Apple Juice 17 times": ["Apple Juice Cooked", 17],
  "Prepare Apple Juice 20 times": ["Apple Juice Cooked", 20],
  "Prepare Apple Juice 25 times": ["Apple Juice Cooked", 25],
  "Prepare Apple Juice 30 times": ["Apple Juice Cooked", 30],
  "Prepare Orange Juice 15 times": ["Orange Juice Cooked", 15],
  "Prepare Orange Juice 20 times": ["Orange Juice Cooked", 20],
  "Prepare Carrot Juice 2 times": ["Carrot Juice Cooked", 2],
  "Prepare Carrot Juice 3 times": ["Carrot Juice Cooked", 3],
  "Prepare Carrot Juice 4 times": ["Carrot Juice Cooked", 4],
  "Cook Carrot Juice 15 times": ["Carrot Juice Cooked", 15],
  "Cook Carrot Juice 20 times": ["Carrot Juice Cooked", 20],
  "Cook Carrot Juice 25 times": ["Carrot Juice Cooked", 25],
  "Prepare Purple Smoothie 5 times": ["Purple Smoothie Cooked", 5],
  "Prepare Purple Smoothie 6 times": ["Purple Smoothie Cooked", 6],
  "Prepare Purple Smoothie 7 times": ["Purple Smoothie Cooked", 7],
  "Prepare Purple Smoothie 10 times": ["Purple Smoothie Cooked", 10],
  "Prepare Purple Smoothie 12 times": ["Purple Smoothie Cooked", 12],
  "Prepare Purple Smoothie 15 times": ["Purple Smoothie Cooked", 15],
  "Prepare Purple Smoothie 17 times": ["Purple Smoothie Cooked", 17],
  "Prepare Purple Smoothie 20 times": ["Purple Smoothie Cooked", 20],
  "Prepare Sour Shake 15 times": ["Sour Shake Cooked", 15],
  "Prepare Sour Shake 20 times": ["Sour Shake Cooked", 20],
  "Prepare Sour Shake 25 times": ["Sour Shake Cooked", 25],
  "Prepare Power Smoothie 2 times": ["Power Smoothie Cooked", 2],
  "Prepare Power Smoothie 3 times": ["Power Smoothie Cooked", 3],
  "Prepare Power Smoothie 4 times": ["Power Smoothie Cooked", 4],
  "Prepare Power Smoothie 5 times": ["Power Smoothie Cooked", 5],
  "Prepare Power Smoothie 6 times": ["Power Smoothie Cooked", 6],
  "Prepare Power Smoothie 7 times": ["Power Smoothie Cooked", 7],
  "Grow Yellow Gladiolus 3 times": ["Yellow Gladiolus Harvested", 3],
  "Grow Yellow Gladiolus 4 times": ["Yellow Gladiolus Harvested", 4],
  "Grow Purple Gladiolus 3 times": ["Purple Gladiolus Harvested", 3],
  "Grow Purple Gladiolus 4 times": ["Purple Gladiolus Harvested", 4],
  "Grow Purple Edelweiss 3 times": ["Purple Edelweiss Harvested", 3],
  "Grow Purple Edelweiss 4 times": ["Purple Edelweiss Harvested", 4],
  "Grow Yellow Edelweiss 3 times": ["Yellow Edelweiss Harvested", 3],
  "Grow Yellow Edelweiss 4 times": ["Yellow Edelweiss Harvested", 4],
  "Grow Blue Clover 3 times": ["Blue Clover Harvested", 3],
  "Grow Blue Clover 4 times": ["Blue Clover Harvested", 4],
  "Grow Blue Clover 5 times": ["Blue Clover Harvested", 5],
  "Grow Yellow Clover 3 times": ["Yellow Clover Harvested", 3],
  "Grow Yellow Clover 4 times": ["Yellow Clover Harvested", 4],
  "Grow Yellow Clover 5 times": ["Yellow Clover Harvested", 5],
  "Grow Red Pansy 2 times": ["Red Pansy Harvested", 2],
  "Grow Red Pansy 3 times": ["Red Pansy Harvested", 3],
  "Grow Yellow Pansy 2 times": ["Yellow Pansy Harvested", 2],
  "Grow Yellow Pansy 3 times": ["Yellow Pansy Harvested", 3],
  "Grow Red Lavender 3 times": ["Red Lavender Harvested", 3],
  "Grow Red Lavender 4 times": ["Red Lavender Harvested", 4],
  "Grow White Lavender 3 times": ["White Lavender Harvested", 3],
  "Grow White Lavender 4 times": ["White Lavender Harvested", 4],
  "Grow Purple Cosmos 2 times": ["Purple Cosmos Harvested", 2],
  "Grow Purple Cosmos 3 times": ["Purple Cosmos Harvested", 3],
  "Grow Purple Cosmos 5 times": ["Purple Cosmos Harvested", 5],
  "Grow Purple Cosmos 6 times": ["Purple Cosmos Harvested", 6],
  "Grow Blue Cosmos 2 times": ["Blue Cosmos Harvested", 2],
  "Grow Blue Cosmos 3 times": ["Blue Cosmos Harvested", 3],
  "Grow Blue Cosmos 5 times": ["Blue Cosmos Harvested", 5],
  "Grow Blue Cosmos 6 times": ["Blue Cosmos Harvested", 6],
  "Grow Red Balloon Flower 3 times": ["Red Balloon Flower Harvested", 3],
  "Grow Red Balloon Flower 4 times": ["Red Balloon Flower Harvested", 4],
  "Grow Red Balloon Flower 5 times": ["Red Balloon Flower Harvested", 5],
  "Grow Blue Balloon Flower 3 times": ["Blue Balloon Flower Harvested", 3],
  "Grow Blue Balloon Flower 4 times": ["Blue Balloon Flower Harvested", 4],
  "Grow Blue Balloon Flower 5 times": ["Blue Balloon Flower Harvested", 5],
  "Grow Purple Daffodil 3 times": ["Purple Daffodil Harvested", 3],
  "Grow Purple Daffodil 4 times": ["Purple Daffodil Harvested", 4],
  "Grow Purple Daffodil 5 times": ["Purple Daffodil Harvested", 5],
  "Grow Red Daffodil 2 times": ["Red Daffodil Harvested", 2],
  "Grow Red Daffodil 3 times": ["Red Daffodil Harvested", 3],
  "Grow Yellow Carnation 3 times": ["Yellow Carnation Harvested", 3],
  "Grow Yellow Carnation 4 times": ["Yellow Carnation Harvested", 4],
  "Grow Blue Carnation 3 times": ["Blue Carnation Harvested", 3],
  "Grow Blue Carnation 4 times": ["Blue Carnation Harvested", 4],
  "Grow White Carnation 3 times": ["White Carnation Harvested", 3],
  "Grow White Carnation 4 times": ["White Carnation Harvested", 4],
  "Grow Red Lotus 3 times": ["Red Lotus Harvested", 3],
  "Grow Red Lotus 4 times": ["Red Lotus Harvested", 4],
  "Grow Yellow Lotus 3 times": ["Yellow Lotus Harvested", 3],
  "Grow Yellow Lotus 4 times": ["Yellow Lotus Harvested", 4],
  "Grow White Lotus 3 times": ["White Lotus Harvested", 3],
  "Grow White Lotus 4 times": ["White Lotus Harvested", 4],
  "Grow Blue Pansy 6 times": ["Blue Pansy Harvested", 6],
  "Grow White Pansy 6 times": ["White Pansy Harvested", 6],
  "Grow White Cosmos 3 times": ["White Cosmos Harvested", 3],
  "Grow White Cosmos 4 times": ["White Cosmos Harvested", 4],
  "Grow Purple Daffodil 6 times": ["Purple Daffodil Harvested", 6],
  "Grow Red Balloon Flower 6 times": ["Red Balloon Flower Harvested", 6],
  "Fish 20 times": ["Rod Casted", 20],
  "Fish 40 times": ["Rod Casted", 40],
  "Fish 50 times": ["Rod Casted", 50],
  "Fish 60 times": ["Rod Casted", 60],
  "Fish 70 times": ["Rod Casted", 70],
  "Fish 80 times": ["Rod Casted", 80],
  "Fish 90 times": ["Rod Casted", 90],
  "Fish 200 times": ["Rod Casted", 200],
  "Fish 220 times": ["Rod Casted", 220],
  "Fish 240 times": ["Rod Casted", 240],
  "Fish 260 times": ["Rod Casted", 260],
  "Fish 250 times": ["Rod Casted", 250],
  "Fish 275 times": ["Rod Casted", 275],
  "Fish 285 times": ["Rod Casted", 285],
  "Fish 300 times": ["Rod Casted", 300],
  "Craft 10 Axes": ["Axe Crafted", 10],
  "Craft 12 Axes": ["Axe Crafted", 12],
  "Craft 15 Axes": ["Axe Crafted", 15],
  "Craft Axes 20 times": ["Axe Crafted", 20],
  "Craft Axes 25 times": ["Axe Crafted", 25],
  "Craft Axes 30 times": ["Axe Crafted", 30],
  "Craft 6 Pickaxes": ["Pickaxe Crafted", 6],
  "Craft 8 Pickaxes": ["Pickaxe Crafted", 8],
  "Craft 10 Pickaxes": ["Pickaxe Crafted", 10],
  "Craft Pickaxes 10 times": ["Pickaxe Crafted", 10],
  "Craft Pickaxes 15 times": ["Pickaxe Crafted", 15],
  "Craft Pickaxes 20 times": ["Pickaxe Crafted", 20],
  "Craft 100 Rods": ["Rod Crafted", 100],
  "Craft 150 Rods": ["Rod Crafted", 150],
  "Craft 200 Rods": ["Rod Crafted", 200],
  "Craft 100 Fishing Rods": ["Rod Crafted", 100],
  "Craft 150 Fishing Rods": ["Rod Crafted", 150],
  "Craft 200 Fishing Rods": ["Rod Crafted", 200],
  "Craft 60 Crab Pots": ["Crab Pot Crafted", 60],
  "Craft 70 Crab Pots": ["Crab Pot Crafted", 70],
  "Craft 80 Crab Pots": ["Crab Pot Crafted", 80],
  "Craft 90 Crab Pots": ["Crab Pot Crafted", 90],
  "Craft 30 Mariner Pots": ["Mariner Pot Crafted", 30],
  "Craft 40 Mariner Pots": ["Mariner Pot Crafted", 40],
  "Craft 50 Mariner Pots": ["Mariner Pot Crafted", 50],
  "Craft 60 Mariner Pots": ["Mariner Pot Crafted", 60],
  "Craft 25 Gold Pickaxes": ["Gold Pickaxe Crafted", 25],
  "Craft 30 Gold Pickaxes": ["Gold Pickaxe Crafted", 30],
  "Craft 35 Gold Pickaxes": ["Gold Pickaxe Crafted", 35],
  "Craft 40 Gold Pickaxes": ["Gold Pickaxe Crafted", 40],
  "Craft 5 Sand Drill": ["Sand Drill Crafted", 5],
  "Craft 10 Sand Drill": ["Sand Drill Crafted", 10],
  "Craft 15 Sand Drill": ["Sand Drill Crafted", 15],
  "Craft 20 Sand Drill": ["Sand Drill Crafted", 20],
  "Craft 25 Sand Drill": ["Sand Drill Crafted", 25],
  "Craft 30 Sand Drill": ["Sand Drill Crafted", 30],
  "Craft 35 Sand Drill": ["Sand Drill Crafted", 35],
  "Chop Trees 10 times": ["Tree Chopped", 10],
  "Chop Trees 15 times": ["Tree Chopped", 15],
  "Chop Trees 20 times": ["Tree Chopped", 20],
  "Chop Trees 25 times": ["Tree Chopped", 25],
  "Chop Trees 30 times": ["Tree Chopped", 30],
  "Chop Trees 100 times": ["Tree Chopped", 100],
  "Chop Trees 120 times": ["Tree Chopped", 120],
  "Chop Trees 150 times": ["Tree Chopped", 150],
  "Chop Trees 200 times": ["Tree Chopped", 200],
  "Chop Trees 250 times": ["Tree Chopped", 250],
  "Chop Trees 450 times": ["Tree Chopped", 450],
  "Chop Trees 500 times": ["Tree Chopped", 500],
  "Chop Trees 550 times": ["Tree Chopped", 550],
  "Chop Trees 600 times": ["Tree Chopped", 600],
  "Mine Stones 5 times": ["Stone Mined", 5],
  "Mine Stones 7 times": ["Stone Mined", 7],
  "Mine Stones 8 times": ["Stone Mined", 8],
  "Mine Stones 10 times": ["Stone Mined", 10],
  "Mine Stones 12 times": ["Stone Mined", 12],
  "Mine Stones 20 times": ["Stone Mined", 20],
  "Mine Stones 50 times": ["Stone Mined", 50],
  "Mine Stones 60 times": ["Stone Mined", 60],
  "Mine Stones 100 times": ["Stone Mined", 100],
  "Mine Stones 135 times": ["Stone Mined", 135],
  "Mine Stones 175 times": ["Stone Mined", 175],
  "Mine Gold 30 times": ["Gold Mined", 30],
  "Mine Gold 38 times": ["Gold Mined", 38],
  "Mine Gold 45 times": ["Gold Mined", 45],
  "Mine Gold 50 times": ["Gold Mined", 50],
  "Mine Gold 55 times": ["Gold Mined", 55],
  "Mine Gold 60 times": ["Gold Mined", 60],
  "Mine Crimstone 20 times": ["Crimstone Mined", 20],
  "Mine Crimstone 22 times": ["Crimstone Mined", 22],
  "Mine Crimstone 24 times": ["Crimstone Mined", 24],
  "Mine Crimstone 28 times": ["Crimstone Mined", 28],
  "Mine Crimstone 32 times": ["Crimstone Mined", 32],
  "Mine Crimstone 36 times": ["Crimstone Mined", 36],
  "Mine Iron 150 times": ["Iron Mined", 150],
  "Mine Iron 175 times": ["Iron Mined", 175],
  "Mine Iron 200 times": ["Iron Mined", 200],
  "Mine Iron 225 times": ["Iron Mined", 225],
  "Mine Iron 250 times": ["Iron Mined", 250],
  "Mine Iron 300 times": ["Iron Mined", 300],
  "Mine Stones 200 times": ["Stone Mined", 200],
  "Mine Stones 250 times": ["Stone Mined", 250],
  "Mine Stones 275 times": ["Stone Mined", 275],
  "Mine Stones 300 times": ["Stone Mined", 300],
  "Drill Oil Reserves 15 times": ["Oil Drilled", 15],
  "Drill Oil Reserves 18 times": ["Oil Drilled", 18],
  "Drill Oil Reserves 21 times": ["Oil Drilled", 21],
  "Pick Blueberries 120 times": ["Blueberry Harvested", 120],
  "Pick Blueberries 150 times": ["Blueberry Harvested", 150],
  "Pick Blueberries 180 times": ["Blueberry Harvested", 180],
  "Pick Blueberries 200 times": ["Blueberry Harvested", 200],
  "Pick Blueberries 250 times": ["Blueberry Harvested", 250],
  "Pick Oranges 100 times": ["Orange Harvested", 100],
  "Pick Oranges 125 times": ["Orange Harvested", 125],
  "Pick Oranges 150 times": ["Orange Harvested", 150],
  "Pick Oranges 160 times": ["Orange Harvested", 160],
  "Pick Oranges 175 times": ["Orange Harvested", 175],
  "Pick Oranges 205 times": ["Orange Harvested", 205],
  "Pick Oranges 250 times": ["Orange Harvested", 250],
  "Pick Apples 60 times": ["Apple Harvested", 60],
  "Pick Apples 75 times": ["Apple Harvested", 75],
  "Pick Apples 90 times": ["Apple Harvested", 90],
  "Pick Apples 125 times": ["Apple Harvested", 125],
  "Pick Apples 150 times": ["Apple Harvested", 150],
  "Pick Apples 175 times": ["Apple Harvested", 175],
  "Pick Tomatoes 150 times": ["Tomato Harvested", 150],
  "Pick Tomatoes 200 times": ["Tomato Harvested", 200],
  "Pick Tomatoes 250 times": ["Tomato Harvested", 250],
  "Pick Tomatoes 300 times": ["Tomato Harvested", 300],
  "Pick Tomatoes 350 times": ["Tomato Harvested", 350],
  "Pick Grapes 36 times": ["Grape Harvested", 36],
  "Pick Grapes 44 times": ["Grape Harvested", 44],
  "Pick Grapes 48 times": ["Grape Harvested", 48],
  "Pick Grapes 52 times": ["Grape Harvested", 52],
  "Pick Grapes 60 times": ["Grape Harvested", 60],
  "Pick Grapes 72 times": ["Grape Harvested", 72],
  "Pick Bananas 80 times": ["Banana Harvested", 80],
  "Pick Bananas 90 times": ["Banana Harvested", 90],
  "Pick Bananas 100 times": ["Banana Harvested", 100],
  "Pick Bananas 120 times": ["Banana Harvested", 120],
  "Pick Bananas 125 times": ["Banana Harvested", 125],
  "Pick Bananas 150 times": ["Banana Harvested", 150],
  "Pick Bananas 175 times": ["Banana Harvested", 175],
  "Pick Bananas 200 times": ["Banana Harvested", 200],
  "Pick Lemons 150 times": ["Lemon Harvested", 150],
  "Pick Lemons 200 times": ["Lemon Harvested", 200],
  "Pick Lemons 250 times": ["Lemon Harvested", 250],
  "Pick Lemons 300 times": ["Lemon Harvested", 300],
  "Pick Lemons 350 times": ["Lemon Harvested", 350],
  "Collect 15 Honey": ["Honey Harvested", 15],
  "Collect 18 Honey": ["Honey Harvested", 18],
  "Collect 21 Honey": ["Honey Harvested", 21],
  "Collect 20 Honey": ["Honey Harvested", 20],
  "Collect 25 Honey": ["Honey Harvested", 25],
  "Collect 30 Honey": ["Honey Harvested", 30],
  "Collect Eggs 60 times": ["Egg Collected", 60],
  "Collect Eggs 75 times": ["Egg Collected", 75],
  "Collect Eggs 80 times": ["Egg Collected", 80],
  "Collect Eggs 100 times": ["Egg Collected", 100],
  "Collect Eggs 125 times": ["Egg Collected", 125],
  "Collect Eggs 150 times": ["Egg Collected", 150],
  "Collect Eggs 175 times": ["Egg Collected", 175],
  "Collect Eggs 200 times": ["Egg Collected", 200],
  "Collect Eggs 225 times": ["Egg Collected", 225],
  "Collect Wool 30 times": ["Wool Collected", 30],
  "Collect Wool 40 times": ["Wool Collected", 40],
  "Collect Wool 50 times": ["Wool Collected", 50],
  "Collect Wool 60 times": ["Wool Collected", 60],
  "Collect Wool 70 times": ["Wool Collected", 70],
  "Collect Wool 75 times": ["Wool Collected", 75],
  "Collect Wool 80 times": ["Wool Collected", 80],
  "Collect Wool 100 times": ["Wool Collected", 100],
  "Collect Wool 125 times": ["Wool Collected", 125],
  "Collect Milk 30 times": ["Milk Collected", 30],
  "Collect Milk 40 times": ["Milk Collected", 40],
  "Collect Milk 50 times": ["Milk Collected", 50],
  "Collect Milk 60 times": ["Milk Collected", 60],
  "Collect Milk 75 times": ["Milk Collected", 75],
  "Collect Milk 100 times": ["Milk Collected", 100],
  "Collect Milk 125 times": ["Milk Collected", 125],
  "Dig 50 times": ["Treasure Dug", 50],
  "Dig 75 times": ["Treasure Dug", 75],
  "Dig 100 times": ["Treasure Dug", 100],
  "Dig 125 times": ["Treasure Dug", 125],
  "Dig 150 times": ["Treasure Dug", 150],
  "Dig 175 times": ["Treasure Dug", 175],
  "Dig 200 times": ["Treasure Dug", 200],
  "Dig 225 times": ["Treasure Dug", 225],
  "Spend 32,000 Coins": ["Coins Spent", 32000],
  "Spend 48,000 Coins": ["Coins Spent", 48000],
  "Spend 64,000 Coins": ["Coins Spent", 64000],
  "Spend 60,606 Coins": ["Coins Spent", 60606],
  "Spend 70,707 Coins": ["Coins Spent", 70707],
  "Spend 80,808 Coins": ["Coins Spent", 80808],
  "Cook 5 Cauliflower Burger": ["Cauliflower Burger Cooked", 5],
  "Harvest Potato 100 times": ["Potato Harvested", 100],
  "Eat 15 Pumpkin Soup": ["Pumpkin Soup Fed", 15],
  "Grow 3 Blue Cosmos": ["Blue Cosmos Harvested", 3],
  "Chop 80 Trees": ["Tree Chopped", 80],
  "Pick 60 Blueberries": ["Blueberry Harvested", 60],
  "Cook 10 Sushi Roll": ["Sushi Roll Cooked", 10],
  "Eat 7 Chowder": ["Chowder Fed", 7],
  "Harvest Olives 8 times": ["Olive Harvested", 8],
  "Mine 10 Crimstone": ["Crimstone Mined", 10],
  "Prepare 15 Bumpkin Detox": ["Bumpkin Detox Cooked", 15],
  "Grow White Pansy 3 times": ["White Pansy Harvested", 3],
  "Cook 5 Fermented Fish": ["Fermented Fish Cooked", 5],
};
