// The engine as the PAGE uses it: one entry point, the same modules the server runs.
// GENERATED by listing every function flowers.html used to carry its own copy of — the page now
// loads these instead (see the loader in its <head>). Regenerate when the page starts using
// another core function.
export { getAgingMaxXP, getAgingSaltCost, getAgingTimeSec } from "./data/cooking.mjs";
export { findCollectible, getAllEquippedWearables, isWearableEquipped } from "./derive/items.mjs";
export { getPriceProduct } from "./engine/buds.mjs";
export { computeSaltYieldPerRake } from "./engine/cooking-cost.mjs";
export { buildingOilBoost, computeFoodXP, detectCookingBoosts, factionWeekKey, getAgingPrimeChance, getAgingPrimeFactor } from "./engine/cooking.mjs";
export { cropMachineCrops, cropMachineOilPerHour, cropMachinePlots, cropMachineSpeedMult, farmHasCropMachine } from "./engine/crop-machine.mjs";
export { _dashHasWearable, computeFlowerMultiplier, dashCalculateDeliveryTickets, dashGetCurrentChapter, dashGetSeasonalTicket, dashHasVipAccess, detectFlowerBoosts, getFlowerChainHours, getFlowerGiftPoints, roadmapGiftRewardLabel, roadmapGiftRewardValue, roadmapItemCost, roadmapKeyValue } from "./engine/gifts-deliveries.mjs";
export { petCumulativeXp, petDailyCalc, petExtraResourceChance, petFeedEnergy, petFetchEnergyBonus, petFetchYield, petLevel, petRequestsAtLevel, petXpBonusMultiplier } from "./engine/pets.mjs";
export { classifyToCategories, expandMultiProductLines, normalizeBoostLine, parseBoostEffects } from "./engine/power-boosts.mjs";
export { _shrineActiveNow, _shrineStatus, activeShrineEffects, calcAnimalFeedCost, calcLavaPitCostPerDay, calcSeedCostPerDay, calcSicknessCost, getAnimalCatSfl, getAnimalDropsPerCycle, getAnimalLevelDistribution, getFeedCostPerUnit, getFeedReductionMult, getOptimalFeedForLevel, toMs, unitToSfl, weatherPlacedInstances } from "./engine/power-costs.mjs";
export { escHTML, formatSec, sflIcon } from "./engine/power-formula.mjs";
export { _ascBandXp, _ascBaseline, _withinAscensionLevel, aoeCoverage, applyBoosts, calcSkillPointCost, calcToolCostPerDay, detectFarmCapacity, detectStockModifiers, farmWearableEquipped, gameResBoostedBase, gameResYield, getAnimalData, getAnimalLevel, getBaseYield, getBumpkinLevel, getCapacityCount, getCount, getCycleSec, getDefaultProduct, getEffectiveStock, getEffectsForCategory, getTotalBumpkinLevel, isAnimalCat, marksToSfl, miningToolsPerDay, sumMergedNodes } from "./engine/power-helpers.mjs";
export { nftUnitPrice, pickCoinsPerSFL } from "./engine/prices.mjs";
export { repayPlanStats } from "./engine/repay-plan.mjs";
export { calcBoostValue, cmGetSeedRestockCount, farmHasWarehouse, gameResUnitsPerDay, getRoadmapSettings, roadmapBuildClones, roadmapCatBreakdown, roadmapCatMix, roadmapCatNet, roadmapCoinsFree, roadmapEffFactor, roadmapInSeason, roadmapItemValue, roadmapMiningChain, roadmapOwnedEffects, roadmapPerPlot, roadmapPrices, roadmapProductNetEff } from "./engine/roadmap.mjs";
export { powerSkillRankVals, skillRankFactor, skillRankMag, skillRankText, skillUpgradeCost } from "./engine/skill-ranks.mjs";
export { diffWindowRange, parseDiffRange } from "./sections/diff.mjs";
export { parseRoiPets } from "./sections/roi.mjs";
export { computeFarmValue } from "./sections/treasury.mjs";
export { _setPowerContext, _getPowerContext, _setRoadmapState } from "./engine/roadmap.mjs";
// Tables the page fills at runtime (applyFlowerBoosts writes the boosted flower times).
export { SEED_DATA as _SEED_DATA } from "./engine/power-helpers.mjs";
// The TICKETY page's chapter goal (reachability, ticket value, the alternatives).
export { ticketGoal } from "./sections/tickets.mjs";
